ALTER TABLE "MusicianProfile"
ADD COLUMN "location" TEXT,
ADD COLUMN "genres" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "instruments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "daw" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "socialLinks" JSONB NOT NULL DEFAULT '{}';
